Repository iii-inc-co-jp/20240417_handson, pull requests merged in 2024-04, with the labels that each got.

#1 適切なタイトル
  sample_haruki.txt
Labels: bug, enhancement

#4 演習用_小川
  sample_ogawa.txt
Labels: enhancement

#7 title first commit
  sample_branch.txt
Labels: bug

#8 演習用_小川2
  sample_ogawa.txt
Labels: enhancement

#9 second commit
  sample_haruki.txt
Labels: enhancement

#11 テストPR_五十嵐
  sample_igarashi.txt
Labels: bug

#10 komittofukumoto
  1234fukumoto.txt
Labels: bug

#20 小川修正
  1234fukumoto.txt
  sample_ogawa.txt
Labels: enhancement
